### ISSUE TITLE
Replace React Native WebView Bible Module with React Native Skia

### ISSUE THREAD

**Issue by smontlouis** [smontlouis/bible-strong#134]
Upgrading our app by replacing the existing Bible module implemented with React Native WebView with React Native Skia. This change aims to enhance performance and provide smoother, more efficient rendering.

This could also fix blank screens some users are having while using the app

**Comment by thesamchris** [comment]
Hey @smontlouis! Chanced upon your Bible Strongs app and this repo and your work is really cool! Thanks for making such a great resource and open-sourcing your efforts! The bible seems to be working really well, so would you be able to share what about the react native webview performance you are looking to solve by moving to React Native Skia?

**Comment by smontlouis** [comment]
Hello!

Thanks for your message :). On some low-end android mobile devices (tecno, infinitix, etc), there is a white screen that appears and I have no idea what it's due to. What's more, the webview is quite complicated to test since you have to test it on a browser.

**Comment by thesamchris** [comment]
Oh okay @smontlouis 

Wouldn't Skia be harder to maintain since it's more low-level compared to something more structured around text?

**Comment by smontlouis** [comment]
From what I know skia can handle paragraphs

**Comment by thesamchris** [comment]
Oh okay noted! Thank you @smontlouis for answering my questions!

**Comment by smontlouis** [comment]
#160
